---
# Run within a Maven source repo to create a build
# Creates a .war build and deploys it on an EC2 server
# WIP
# ex: ansible-playbook deploy_war_test.yaml -e "env=STAGING dir=$PWD"

# Create a build
- hosts: 127.0.0.1
  connection: local
  vars:
    env: "{{ env }}"
  tasks:
    - name: Building a .war for {{ env }}
      command: mvn clean package -P {{ env }}
      args:
        chdir:  "{{ dir }}"
      register: out

    - debug: var=out.stdout_lines

# Copy build to remote
- hosts: abc.someapp.com
  gather_facts: false
  vars:
    remote_user: ec2-user
  tasks:
    - name: Copying build to {{ env }}
      copy:
        src: "{{ item }}"
        dest: "/tmp"
      with_fileglob:
        - "{{ dir }}/target/*.war"

# Undeploy current WAR build


# Deploy new WAR build
